[package]
name = "autumn-boot-sea-streamer"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sea-streamer = "0.5.0"
