[workspace]
members = [
    "autumn-boot",
    "autumn-boot-macro",
    "autumn-boot-web",
    "autumn-boot-job",
    "autumn-boot-redis",
    "autumn-boot-sqlx",
    "autumn-boot-sea-orm",
    "autumn-boot-sea-streamer",
    "autumn-boot-actuator",
    "autumn-boot-mail",
    "examples/web",
    "examples/job",
]
default-members = ["autumn-boot", "autumn-boot-*"]
