[workspace]
members = [
    "autumn-boot",
    "autumn-boot-macro",
    "autumn-boot-web",
    "autumn-boot-schedule",
    "autumn-boot-redis",
    "autumn-boot-sqlx",
    "autumn-boot-sea-orm",
    "autumn-boot-sea-streamer",
]
